### ISSUE TITLE
运行到礼包达人报错领取不了

### ISSUE THREAD

**Issue by 9iulii** [fzls/djc_helper#234]
Traceback (most recent call last):
  File "util.py", line 731, in wrapper
  File "djc_helper.py", line 895, in take_mobile_game_gift
  File "djc_helper.py", line 1353, in get_mobile_game_gifts
KeyError: 'data'

请帮忙看看是什么原因造成的呀，其他一切正常。

**Comment by fzls** [comment]
> Traceback (most recent call last): File "util.py", line 731, in wrapper File "djc_helper.py", line 895, in take_mobile_game_gift File "djc_helper.py", line 1353, in get_mobile_game_gifts KeyError: 'data'
> 
> 请帮忙看看是什么原因造成的呀，其他一切正常。

这个接口暂时没接入，不用管。或者你可以自己尝试抓包接一下这个
